<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="HolderWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/HolderWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/HolderWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://ws.holder/">
    <import location="localhost_8080/Holder.wsdl" namespace="http://ws.holder/"/>
    <plnk:partnerLinkType name="HolderServiceLinkType">
        <plnk:role name="HolderServiceRole" portType="ns:HolderService"/>
    </plnk:partnerLinkType>
</definitions>
